# Prove

In [3]:
import numpy as np
print(np.__version__)

2.2.4


In [4]:
import numpy as np

a = np.array([2, 3, 5, 7, 11])
print(a)
print(type(a))

[ 2  3  5  7 11]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]
