# Selfcheck Exercise

#### Ex 7.2

##### 2. Create a one-dimensional `array` from a list comprehension that produces the even integers from 2 through 20. 

In [1]:
import numpy as np

np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### 3. Create a 2-by-5 `array` containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row. 


In [2]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

#### Ex 7.3

##### For the two-dimensional array in the previous section’s Self Check, display the number of dimensions and shape of the array.

In [4]:
import numpy as np

a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 5)

#### Ex 7.5

##### Use NumPy function `arange` to create an `array` of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 `array`.


In [7]:
import numpy as np

np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

#### Ex 7.6

##### Use `%timeit` to compare the execution time of the following two statements. The first uses a list comprehension to create a list of the integers from 0 to 9,999,999 then totals them with the built-in `sum` function. The second statement does the same thing using an `array` and its `sum` method.
```python
sum([x for x in range(10_000_000)])
np.arange(10_000_000).sum()
```

In [9]:
import numpy as np

In [10]:
%timeit sum([x for x in range(10_000_000)])

399 ms ± 66.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit np.arange(10_000_000).sum()

13.8 ms ± 1.29 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Ex 7.7

##### Create an array of the values from 1 through 5 then use broadcasting to square each value.

In [13]:
import numpy as np

np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])